language: cpp
compiler: gcc
dist: bionic
os: linux
before_script:
- sudo apt-get update
- sudo apt-get upgrade
- sudo apt-get install libboost-all-dev git automake autoconf dh-make fakeroot libpcsclite-dev
  pcscd pcsc-tools -y
script:
- echo $TRAVIS_TAG
- mkdir libgtop11dotnet-1.1
- wget -qO- https://github.com/GregsCode12/libgtop11dotnet-1/tarball/Fix-build-code| tar  -xvzf - -C libgtop11dotnet-1.1 --strip 1
- cd libgtop11dotnet-1.1
- dh_make --createorig --single -y
- dpkg-buildpackage -us -uc
deploy:
  provider: releases
  skip_cleanup: true
  token:
     secure: "Wr8ietK+dbRbuWwNh3qulufJgAwcmcOC24v2QJX+RFR+S6+rIbwoueVxmJy3s2Axd30yYoPvCBRQwVduukNm7PzNqo9gcZqoWnxpYOQlYIkvDNJV7NjmtLh1c6M7+H3zq4aEQPw7ZTy0rxJOC6hB0RPCG7cbyR3hUI9DlrbwiE9zSIrGI8R1jK5ydJKdGxZ4pz7AfeT1x2bzuzowlekFm90JdgS9McxrxVOgXZAuoqcVCHg7DVHAzIBfZ6PTJCI+NVXCXOSawILAG9bIH8WlZeYduDALps5Q0wZn00WjYpxzDxV56lWgdNy2LGJ3pLqDmWgyxh9v826O//BGOS0IGBMdkTHExtY3g/JhfIBlzzX8bONPLOXDfZJYWgcvw6jEOFr9tSL/MScDQndE3ZVLZFOAEYaloWAOPctV+g58d3UZs+h4iByEfqnBKUVLbHCNWaJ2TPN7TrdMGx8hk20guA/rvPjBUlsKEVxFw5Kwr2qzYAEXQ1IKri6/UB6JZzd5KorVbkoT2BK4XcjHJKUcws1VSM2sPjcbrJosQ5ekuwpF6Hq71FiRuNzAxrfZ5vclsJLelfaAS/GvdNqk0hZ1tRmjROFKv1f44O8zwZHh+20OHOEzLsI7a0E2aRShgPTrRFXzSKlUXNt2W3OXuLWgw5PWF89VUTOrINUvWkg/So0="
  username: "GregsCode12"
  password:
     secure: "jGFORDOLArzLfyx9gOIHF7fiKJG7N4ZL2v0AYqwXsB/yJftYBfA+ldHgbdP2n708NxxRXDW1y6x4MGs5ObekMvv+yLPMy0rT6dYXWZCPXCx5Rqedn/5W+ixYab04+QJOD//PHZh/U/8V/WOX+fhGqZZsXN2u4ZA51CF3tIqrNkbtC2bRwHjAudczSzaDFZXwvIHtNQgAZPhMMK5mjd/QhCiX6Mp73qrW30lTvEcubsM/bfa/x8y71LT2tiEdV6Ehz34NsXhbWXj7EoQaCYyiGtPDCgji67NXLvKaeSP2ee4kSEs+VRoN/apzaVXN/MVJstiLagjYoyZqRjK9C0VJ/G8oHKXtniv/YB0SEwiGX+oi7feJKQjYnCwzqaYj9Rik0VNuZu5YvaFZwqFF8H90OSeaC99f84mMH8em70wIdzGR67q4GFvApaWE0WLmUMNV6KM/TtbLIFHTW+Lz8r2nDSbSXcXI+ildpRtLWT5fpko7iAW/IBJH8V9ugKnREyUjZLIDwFFxCxwFmZtXp6SzXS1ITGT3kxPn2/Y2YhDSLgsE5JWQwoNVc4HNx8CbzNxUQVu+tJpX3jNFG1BXlx96BN0Blj8/p4J0xneGBsxnAuLB+LIswA3kfSripjE7YImFet+RR98v2ciRse8dSF1XJhLrxTJlg2ajeg9Fo5+4KXc="
  file_glob: true
  file: 
     "/home/travis/build/GOGO-d-o-o/libgtop11dotnet/libgtop11dotnet-1.1"
  on: 
    tags: true
    branch: master
