language: cpp
compiler: gcc
dist: bionic
addons:
  artifacts: true
before_script:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install libboost-all-dev git automake autoconf dh-make fakeroot libpcsclite-dev pcscd pcsc-tools -y

script:
  - mkdir libgtop11dotnet-1.1
  - wget -qO- https://github.com/GregsCode12/libgtop11dotnet-1/tarball/Fix-build-code| tar  -xvzf - -C libgtop11dotnet-1.1 --strip 1
  - cd libgtop11dotnet-1.1
  - dh_make --createorig --single -y
  - dpkg-buildpackage -us -uc

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token:
    secure: a88XdkYhLTnjlwX1NDFV9bsyzQ7B8ZjTEtHxFoEztKS6fR/iBVNqGgxPT1ykB/J5Ie44P5qDFUWM1XYT6PodMuz/6+KSQb44yZda+VRboTROIPjKWDTi3FSuoO4l1ZVshUQIrgl9xNMxXs8Os3U4LxZ+6krAMRwtv9l5Bp3wwbOAyftAzAEk27/1KFi5U1GJ5KnTH5zb8/m07jha6df1ZzWyNSYyCkEkzTNA0V0O6t5HdNUh8TzjKaoHADJ8RW2EaHYIKVrUACtkybhIkx/puYMhCM6k4f7CKFHLgZ0OBnW7ARi/cWGyP8kpCK9VCOvsiDctA6GAZ7KdVtvQEQgSzVlgjqVuLf+GRUXUlJ6xmHqDYRvVPu9AJd4mM8IIpe+y2SlWLOWZh+XUMnrOZZUo8gKk2OdW4YqKkzDhHmE7tP9FLJv8LQrqt3HI5GGcG8kirHFWqQOxP5qO6123Ir1XvJ+RNxiFs6cGW1AjouPxyOAm+WmYI3ZJ1P97yDHtaBf/zda2uodQDF3kSEzmbARUjxZTvNwgUHsRs3wHrGs1vbJKERI87UNCvsoFt438pK/b9hJKDy0ZUGsTqDN7wkYuAz9I597Ne/I9xgRdkDCXI2P/OWaQTtc3eVYnZ10cGA7CwgEmyr2WLXCAbxt+KccaHlupCgDIWuWQqLv1d9gFw94=
