language: cpp
compiler: gcc
dist: bionic
os: linux
addons:
  artifacts: true
before_script:
- sudo apt-get update
- sudo apt-get upgrade
- sudo apt-get install libboost-all-dev git automake autoconf dh-make fakeroot libpcsclite-dev
  pcscd pcsc-tools -y
- sudo mkdir -p /package/libgtop11dotnet-1.1
script:
- sudo cp -r * /package/libgtop11dotnet-1.1
- cd /package/libgtop11dotnet-1.1
- sudo dh_make --createorig --single -y
- sudo dpkg-buildpackage -us -uc -sa -b
before_deploy: sudo chown -R travis:travis /home/travis/
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
     secure: "gb773hvi/bayb8AT66qoU/ynqgWm9vmyTjsnLaYAOl67qI2h5NbAGxxgf0jyQwss//gEZPLfYX37k5sqkk25ud2mRQP4bAxBrwgxcJgrcJdv2fejFUWb1xokYTp6xeyrssT2qlcT9XTHzDfNxtLsbGvmz9aU53ATjhxH4sJSg7WHt55aHz60v8ODlBv8IBXKjtsRSzuSeoT5mpB3deIaoUorcPntvSgdZXedFUErHxPtXBwnZn8vjO7VK91kY1gOJga0GMkkSWBryy+CBDVXL69zAr2K3ldwINByfKUGxUKrPPCd2JN5YZ6yfRTczYHzEVEroZcKeprXY+7UG9ng0Gog4uDHpeUs49GZCyQKs8howazU25IY5CfwmUgKlEUdZP65WY84bc1g19CoMe4yuASt8Ez8H17aPIXgsBy0brYZxmuVZehfkJcR0S6HiPFxLe9M7agZ5ZL+o27CDM7OU4t3S7ahgr8ID5PJc1XesxMSpmyGtk58kzKQIWlM873HwyBImMuKJlnuOagiWr3vsEii2pzmAk5tKulRc99afrVpIc/wkhbha+u11tloFL6yhhitmsufR27+1GEmSJiWrALchMYXYOAhNfQAVF232x25STrHpkqVL0kSrdp0bhhuTeZQ5YOV9GoTf+L5h3GhkDSIEmGTHZIZgFX8kdpDvIs="
<<<<<<< HEAD
   on: 
    tags: false
=======
   keep_history: true
   on:
      branch: master
>>>>>>> testing
