language: cpp
compiler: gcc
dist: bionic
before_script:
- sudo apt-get update
- sudo apt-get upgrade
- sudo apt-get install libboost-all-dev git automake autoconf dh-make fakeroot libpcsclite-dev
  pcscd pcsc-tools -y
- sudo mkdir -p /package/libgtop11dotnet-1.1
script:
- sudo cp * /package/libgtop11dotnet-1.1 -r
- cd /package/libgtop11dotnet-1.1
- sudo dh_make --createorig --single -y
- sudo dpkg-buildpackage -us -uc -sa
deploy:
  provider: releases
  skip_cleanup: true
  token:
     secure: "gb773hvi/bayb8AT66qoU/ynqgWm9vmyTjsnLaYAOl67qI2h5NbAGxxgf0jyQwss//gEZPLfYX37k5sqkk25ud2mRQP4bAxBrwgxcJgrcJdv2fejFUWb1xokYTp6xeyrssT2qlcT9XTHzDfNxtLsbGvmz9aU53ATjhxH4sJSg7WHt55aHz60v8ODlBv8IBXKjtsRSzuSeoT5mpB3deIaoUorcPntvSgdZXedFUErHxPtXBwnZn8vjO7VK91kY1gOJga0GMkkSWBryy+CBDVXL69zAr2K3ldwINByfKUGxUKrPPCd2JN5YZ6yfRTczYHzEVEroZcKeprXY+7UG9ng0Gog4uDHpeUs49GZCyQKs8howazU25IY5CfwmUgKlEUdZP65WY84bc1g19CoMe4yuASt8Ez8H17aPIXgsBy0brYZxmuVZehfkJcR0S6HiPFxLe9M7agZ5ZL+o27CDM7OU4t3S7ahgr8ID5PJc1XesxMSpmyGtk58kzKQIWlM873HwyBImMuKJlnuOagiWr3vsEii2pzmAk5tKulRc99afrVpIc/wkhbha+u11tloFL6yhhitmsufR27+1GEmSJiWrALchMYXYOAhNfQAVF232x25STrHpkqVL0kSrdp0bhhuTeZQ5YOV9GoTf+L5h3GhkDSIEmGTHZIZgFX8kdpDvIs="
  username: "GregsCode12"
  password:
     secure: "jGFORDOLArzLfyx9gOIHF7fiKJG7N4ZL2v0AYqwXsB/yJftYBfA+ldHgbdP2n708NxxRXDW1y6x4MGs5ObekMvv+yLPMy0rT6dYXWZCPXCx5Rqedn/5W+ixYab04+QJOD//PHZh/U/8V/WOX+fhGqZZsXN2u4ZA51CF3tIqrNkbtC2bRwHjAudczSzaDFZXwvIHtNQgAZPhMMK5mjd/QhCiX6Mp73qrW30lTvEcubsM/bfa/x8y71LT2tiEdV6Ehz34NsXhbWXj7EoQaCYyiGtPDCgji67NXLvKaeSP2ee4kSEs+VRoN/apzaVXN/MVJstiLagjYoyZqRjK9C0VJ/G8oHKXtniv/YB0SEwiGX+oi7feJKQjYnCwzqaYj9Rik0VNuZu5YvaFZwqFF8H90OSeaC99f84mMH8em70wIdzGR67q4GFvApaWE0WLmUMNV6KM/TtbLIFHTW+Lz8r2nDSbSXcXI+ildpRtLWT5fpko7iAW/IBJH8V9ugKnREyUjZLIDwFFxCxwFmZtXp6SzXS1ITGT3kxPn2/Y2YhDSLgsE5JWQwoNVc4HNx8CbzNxUQVu+tJpX3jNFG1BXlx96BN0Blj8/p4J0xneGBsxnAuLB+LIswA3kfSripjE7YImFet+RR98v2ciRse8dSF1XJhLrxTJlg2ajeg9Fo5+4KXc="
  file_glob: true
  file: 
     "/home/travis/build/GOGO-d-o-o/libgtop11dotnet/libgtop11dotnet-1.1"
  on: 
    tags: false
